/*
  COMPLETE SUPABASE SQL SCHEMA FOR BRIGHT FUTURE ACADEMY
  
  Instructions:
  1. Copy ALL the code below.
  2. Paste it into your Supabase SQL Editor.
  3. Run it.
  
  This script is idempotent (safe to run multiple times). 
  It adds missing columns, creates missing tables, and resets security policies.
*/

-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. ENUMS
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('admin', 'teacher', 'student', 'cashier', 'exam_officer');
    ELSE
        ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'cashier';
        ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'exam_officer';
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fee_payment_status') THEN
        CREATE TYPE fee_payment_status AS ENUM ('Paid', 'Partial', 'Not Paid');
    END IF;
END $$;

-- 2. TABLES
-- Profiles
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  username TEXT UNIQUE,
  email TEXT NOT NULL,
  role user_role DEFAULT 'teacher',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Settings
CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  school_name TEXT DEFAULT 'Bright Future Academy',
  school_logo_url TEXT,
  school_motto TEXT DEFAULT 'Knowledge is Power',
  current_term TEXT DEFAULT '1st',
  current_session TEXT DEFAULT '2025/2026',
  next_term_begins TEXT,
  principal_signature_url TEXT,
  id_card_header_color TEXT DEFAULT '#2563eb',
  id_card_accent_color TEXT DEFAULT '#3b82f6',
  id_card_primary_text_color TEXT DEFAULT '#0f172a',
  id_card_font_style TEXT DEFAULT 'helvetica',
  CONSTRAINT single_row CHECK (id = 1)
);

-- Classes
CREATE TABLE IF NOT EXISTS classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name TEXT NOT NULL UNIQUE,
  teacher_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Subjects
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Students
CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  middle_name TEXT,
  gender TEXT,
  admission_number TEXT UNIQUE NOT NULL,
  class_id BIGINT REFERENCES classes(id) ON DELETE SET NULL,
  teacher_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  parent_name TEXT,
  parent_contact TEXT,
  address TEXT,
  category TEXT DEFAULT 'Boarding',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Attendance (Fixing the reported missing table)
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT CHECK (status IN ('Present', 'Absent')),
  remark TEXT,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(student_id, date)
);

-- Announcements (Fixing the reported missing table)
CREATE TABLE IF NOT EXISTS announcements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  target_role TEXT NOT NULL DEFAULT 'all',
  target_class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Fee Records
CREATE TABLE IF NOT EXISTS fee_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  total_amount NUMERIC DEFAULT 0,
  amount_paid NUMERIC DEFAULT 0,
  balance NUMERIC,
  status fee_payment_status DEFAULT 'Not Paid',
  results_locked BOOLEAN DEFAULT TRUE,
  last_updated_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(student_id, term, session)
);

-- Fee Standards
CREATE TABLE IF NOT EXISTS fee_standards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(class_id, term, session)
);

-- Results
CREATE TABLE IF NOT EXISTS results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  ca1_score NUMERIC DEFAULT 0,
  ca2_score NUMERIC DEFAULT 0,
  exam_score NUMERIC DEFAULT 0,
  total_score NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(student_id, subject_id, term, session)
);

-- Class Subjects (Pivot)
CREATE TABLE IF NOT EXISTS class_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  UNIQUE(class_id, subject_id)
);

-- Teacher Classes (Pivot)
CREATE TABLE IF NOT EXISTS teacher_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  UNIQUE(teacher_id, class_id)
);

-- Teacher Subjects (Pivot)
CREATE TABLE IF NOT EXISTS teacher_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  UNIQUE(teacher_id, subject_id)
);

-- Psychomotor Skills & Affective Domain
CREATE TABLE IF NOT EXISTS psychomotor_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  term TEXT NOT NULL,
  session TEXT NOT NULL,
  handwriting INTEGER DEFAULT 0,
  fluency INTEGER DEFAULT 0,
  games INTEGER DEFAULT 0,
  sports INTEGER DEFAULT 0,
  gymnastics INTEGER DEFAULT 0,
  handling_tools INTEGER DEFAULT 0,
  drawing_painting INTEGER DEFAULT 0,
  crafts INTEGER DEFAULT 0,
  musical_skills INTEGER DEFAULT 0,
  punctuality INTEGER DEFAULT 0,
  neatness INTEGER DEFAULT 0,
  politeness INTEGER DEFAULT 0,
  honesty INTEGER DEFAULT 0,
  relationship_with_others INTEGER DEFAULT 0,
  leadership INTEGER DEFAULT 0,
  emotional_stability INTEGER DEFAULT 0,
  health INTEGER DEFAULT 0,
  self_control INTEGER DEFAULT 0,
  attentiveness INTEGER DEFAULT 0,
  perseverance INTEGER DEFAULT 0,
  days_present INTEGER DEFAULT 0,
  days_absent INTEGER DEFAULT 0,
  total_days INTEGER DEFAULT 0,
  teacher_remark TEXT,
  principal_remark TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(student_id, term, session)
);

-- 3. ENSURE COLUMNS EXIST (FOR EXISTING TABLES)
DO $$ BEGIN
    -- Students table fixes
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='gender') THEN
        ALTER TABLE students ADD COLUMN gender TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='address') THEN
        ALTER TABLE students ADD COLUMN address TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='category') THEN
        ALTER TABLE students ADD COLUMN category TEXT DEFAULT 'Boarding';
    END IF;

    -- Settings table fixes
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='settings' AND column_name='next_term_begins') THEN
        ALTER TABLE settings ADD COLUMN next_term_begins TEXT;
    END IF;

    -- Fee Records fixes
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='fee_records' AND column_name='balance') THEN
        ALTER TABLE fee_records ADD COLUMN balance NUMERIC GENERATED ALWAYS AS (total_amount - amount_paid) STORED;
    END IF;
END $$;

-- 4. HELPER FUNCTIONS
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean SECURITY DEFINER SET search_path = public, auth AS $$
BEGIN
  RETURN (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' OR 
         EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role::text = 'admin');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS boolean SECURITY DEFINER SET search_path = public, auth AS $$
BEGIN
  RETURN (auth.jwt() -> 'user_metadata' ->> 'role') IN ('admin', 'teacher', 'cashier', 'exam_officer') OR 
         EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role::text IN ('admin', 'teacher', 'cashier', 'exam_officer'));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.is_cashier()
RETURNS boolean SECURITY DEFINER SET search_path = public, auth AS $$
BEGIN
  RETURN (auth.jwt() -> 'user_metadata' ->> 'role') = 'cashier' OR 
         EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role::text = 'cashier');
END;
$$ LANGUAGE plpgsql;

-- 5. ENABLE RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE fee_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE fee_standards ENABLE ROW LEVEL SECURITY;
ALTER TABLE results ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE psychomotor_skills ENABLE ROW LEVEL SECURITY;

-- 6. POLICIES (Reset and Recreate)
DO $$ 
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', r.policyname, r.tablename);
    END LOOP;
END $$;

-- Profiles
CREATE POLICY "Profiles viewable by authenticated" ON profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admin manage profiles" ON profiles FOR ALL USING (is_admin());

-- Settings
CREATE POLICY "Settings viewable by everyone" ON settings FOR SELECT USING (true);
CREATE POLICY "Admin manage settings" ON settings FOR ALL USING (is_admin());

-- Classes & Subjects
CREATE POLICY "Public view classes" ON classes FOR SELECT USING (true);
CREATE POLICY "Admin manage classes" ON classes FOR ALL USING (is_staff());

CREATE POLICY "Public view subjects" ON subjects FOR SELECT USING (true);
CREATE POLICY "Admin manage subjects" ON subjects FOR ALL USING (is_staff());

-- Students
CREATE POLICY "Staff view students" ON students FOR SELECT USING (is_staff());
CREATE POLICY "Admin manage students" ON students FOR ALL USING (is_staff());

-- Attendance
CREATE POLICY "Everyone view attendance" ON attendance FOR SELECT USING (true);
CREATE POLICY "Staff manage attendance" ON attendance FOR ALL USING (is_staff());

-- Announcements
CREATE POLICY "View announcements" ON announcements FOR SELECT USING (true);
CREATE POLICY "Manage announcements" ON announcements FOR ALL USING (is_staff());

-- Fees
CREATE POLICY "Staff view fee_records" ON fee_records FOR SELECT USING (is_staff());
CREATE POLICY "Admin manage fee_records" ON fee_records FOR ALL USING (is_admin() OR is_cashier());
CREATE POLICY "Students view own fee_records" ON fee_records FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM students s
    JOIN profiles p ON s.admission_number = p.username
    WHERE s.id = fee_records.student_id AND p.id = auth.uid()
  )
);

CREATE POLICY "Staff view fee_standards" ON fee_standards FOR SELECT USING (is_staff());
CREATE POLICY "Admin manage fee_standards" ON fee_standards FOR ALL USING (is_admin());
CREATE POLICY "Public view fee_standards" ON fee_standards FOR SELECT USING (true);

-- Results
CREATE POLICY "Staff view results" ON results FOR SELECT USING (is_staff());
CREATE POLICY "Staff manage results" ON results FOR ALL USING (is_staff());
CREATE POLICY "Students view own results" ON results FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM students s
    JOIN profiles p ON s.admission_number = p.username
    WHERE s.id = results.student_id AND p.id = auth.uid()
  )
);

-- Pivot
CREATE POLICY "Public view class_subjects" ON class_subjects FOR SELECT USING (true);
CREATE POLICY "Admin manage class_subjects" ON class_subjects FOR ALL USING (is_staff());

CREATE POLICY "Public view teacher_classes" ON teacher_classes FOR SELECT USING (true);
CREATE POLICY "Admin manage teacher_classes" ON teacher_classes FOR ALL USING (is_admin());

CREATE POLICY "Public view teacher_subjects" ON teacher_subjects FOR SELECT USING (true);
CREATE POLICY "Admin manage teacher_subjects" ON teacher_subjects FOR ALL USING (is_admin());

CREATE POLICY "Staff view psychomotor_skills" ON psychomotor_skills FOR SELECT USING (is_staff());
CREATE POLICY "Staff manage psychomotor_skills" ON psychomotor_skills FOR ALL USING (is_staff());
CREATE POLICY "Students view own psychomotor_skills" ON psychomotor_skills FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM students s
    JOIN profiles p ON s.admission_number = p.username
    WHERE s.id = psychomotor_skills.student_id AND p.id = auth.uid()
  )
);

-- 7. TRIGGERS
-- Handle New User
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  is_first_user BOOLEAN;
  target_role user_role := 'teacher';
BEGIN
  SELECT NOT EXISTS (SELECT 1 FROM public.profiles) INTO is_first_user;
  
  IF is_first_user THEN
    target_role := 'admin';
  ELSIF NEW.raw_user_meta_data->>'role' IS NOT NULL THEN
    target_role := (NEW.raw_user_meta_data->>'role')::user_role;
  END IF;

  INSERT INTO public.profiles (id, name, username, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', 'User'),
    COALESCE(NEW.raw_user_meta_data->>'username', NEW.email),
    COALESCE(NEW.email, ''),
    target_role
  )
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    username = EXCLUDED.username,
    role = EXCLUDED.role;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Sync Role back to Auth Metadata
CREATE OR REPLACE FUNCTION public.sync_profile_to_auth()
RETURNS trigger AS $$
BEGIN
  UPDATE auth.users
  SET raw_user_meta_data = 
    COALESCE(raw_user_meta_data, '{}'::jsonb) || 
    jsonb_build_object('role', NEW.role::text, 'name', NEW.name, 'username', NEW.username)
  WHERE id = NEW.id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_profile_update ON profiles;
CREATE TRIGGER on_profile_update
  AFTER INSERT OR UPDATE ON profiles
  FOR EACH ROW EXECUTE PROCEDURE public.sync_profile_to_auth();

-- 8. INITIAL DATA
INSERT INTO settings (id, school_name, school_motto)
VALUES (1, 'Bright Future Academy', 'Knowledge is Power')
ON CONFLICT (id) DO NOTHING;
